package BingoCaller::Model::DBIC;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'BingoCaller::Schema',
    
    connect_info => {
        dsn => 'dbi:SQLite:root/database',
        user => '',
        password => '',
    }
);

=head1 NAME

BingoCaller::Model::DBIC - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<BingoCaller>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<BingoCaller::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.39

=head1 AUTHOR

Andy Brown

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
